### ISSUE TITLE
Not received funds 

### ISSUE THREAD

**Issue by envymc1** [electroneum/electroneum-blockchain-explorer#16]
I withdrew yesterday to adress etnk2Q7LZXgfXitHFdT5y8YbGMjh3t3zPXQsSVmWPM6ffF8m6Dtqbiefw6p7tHmBCaB4C88sf3ZAqX8MFuKbSGPW2rxsFBcEqv
But havent received it can someone please help me thanks

**Comment by nandyala001** [comment]
Hi this  payment  is not received please solve the problem thank you sir

**Comment by nandyala001** [comment]
This is  my address I'd   etnk2Q7LZXgfXitHFdT5y8YbGMjh3t3zPXQsSVmWPM6ffF8m6Dtqbiefw6p7tHmBCaB4C88sf3ZAqX8MFuKbSGPW2rxsFBcEqv  
And this is my payment I'd  b9e6fda80904fd0460c0f73ef2d3046792fef21e009fed052322f7b1c477faaa
And

**Comment by envymc1** [comment]
Hi here is  screenshot of transaction that I never received

**Comment by nandyala001** [comment]
![Uploading Screenshot_20201230-133613_Electroneum.jpg…]()

**Comment by ashot5522** [comment]
This is my address I'd
etnk2Q7LZXgfXitHFdT5y8YbGMjh3t3zPXQsSVmWPM6ffF8m6Dtqbiefw6p7tHmBCaB4C88sf3ZAqX8MFuKbSGPW2rxsFBcEqv 
this payment is not received please solve the problem thank you

**Comment by ashot5522** [comment]
Хеш транзакции (TxHash)
2137925809fad3affbc15e2e3e2289f5a13dcc24544f641c26f50dd4f0e0771c
Приватный ключ TX
76b848edf0954ccb60907ead0bf9eeee6cc7967b7ade69cd2583d7ce88092002
