### ISSUE TITLE
Not received Etn

### ISSUE THREAD

**Issue by Felixbty06** [electroneum/electroneum-blockchain-explorer#18]
I have send Etn to destination address: etnjzydNicf8qV4eigKm6wigAi3gGrfdvE6bz5tw7ktQBEUzDy2uay7KMY7F3qcxH2eNecPP3T8qcb5JYxrNVv1c2EdiCSsoBn without mentioning payment Id from electroneum app
But have not received by receipent and also it's not showing in Electroneum Wallet too
Please help.me out to recover it

**Comment by NoksMthethwa** [comment]
Felixbty06 I am experiencing the same issue. I sent my coins but nothing on my other wallet

**Comment by Felixbty06** [comment]
How should we recover

**Comment by Brightsvg** [comment]
Message me @Emeraldvee5@gmail.com for assistance
