### ISSUE TITLE
unable to build due to missing header file

### ISSUE THREAD

**Issue by cambazz** [electroneum/electroneum-blockchain-explorer#2]
Hello,
I tried to compile the blockchain-explorer but I failed due to:

`/
ETN/electroneum-blockchain-explorer/src/monero_headers.h:19:37: fatal error: release/version/version.h: No such file or directory

While building  CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o

I previously compiled electroneumd from source and installed all the dependencies. 

Is there a build procedure for this? I used mkdir build; cd build; cmake ..; make and used build produres described in electroneumd, but failed.

Any ideas/help greatly appreciated,

~C

**Comment by hugoboosh** [comment]
Check your path. It seems like you have a ' at the beginning. Also, do you have a directory called ETN right at root or were you working off of relative path?

**Comment by hugoboosh** [comment]
I haven't messed with this project yet so don't take my comment as if I know fr9m experience, just guessing based on your post.

**Comment by Alia-morsi** [comment]
I'm facing the same issue. How has this been resolved?
