### ISSUE TITLE
Wrong block size limit given in API

### ISSUE THREAD

**Issue by benjaminoo** [electroneum/electroneum-blockchain-explorer#7]
The wrong block size limit is given at https://blockexplorer.electroneum.com/api/networkinfo. It now shows a constant 300kb whereas the current minimum limit is around 150kb.

It worked perfectly before the tech update/fork on 31 May 2018.

I guess it will be a simple fix since the [front page](https://blockexplorer.electroneum.com/) of the block explorer shows the correct value.

**Comment by ChrisCharrison** [comment]
Block size limit is 300kb. It's 2x the effective median, which is 150kB for median size <=150kB.
